name: Test checkout
on: [push]
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
        run: |
          echo $(pwd)
          cd vz-crd
          ls
          
