apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
  name: VZ_INSTALLATION_NAME
spec:
  profile: VZ_PROFILE
  components:
    dns:
      wildcard:
        domain: DNS_WILDCARD_DOMAIN
