apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
  name: VZ_INSTALLATION_NAME
spec:
  profile: VZ_PROFILE
  components:
    keycloak:
      mysql:
        volumeSource:
          persistentVolumeClaim:
            claimName: mysql  # Use the "mysql" PVC template for the MySQL volume configuration
  volumeClaimSpecTemplates:
  - metadata:
      name: mysql      
    spec:
      resources:
        requests:
          storage: 100Gi
