apiVersion: install.verrazzano.io/v1alpha1
kind: Verrazzano
metadata:
  name: VZ_INSTALLATION_NAME
spec:
  profile: VZ_PROFILE
  components:
    certManager:
      certificate:
        acme:
          provider: letsEncrypt
          emailAddress: VZ_ACME_EMAIL
          environment: staging
