name: Deploy Verrazzano
on:
  workflow_call:
    inputs:
      vz_crd_filename:
        required: false
        type: string  
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      - name: List checked-out files
        run: |
          echo $(pwd)
          cat ${{ inputs.vz_crd_filename }}
  
