name: GitHub Actions Demo
on: [push]
jobs:
  test_curl:
    runs-on: ubuntu-latest
    steps:
      - name: Get Verrazzano console status
        uses: wei/curl@master
        with:
          args: https://${{secrets.VZ_CONSOLE_URL}}
