name: GitHub Actions Demo for V8o on Azure
on: [push]
env:
  azCliVersion: 2.6.0
jobs:
  azure_login:
    runs-on: ubuntu-latest
    steps:
      - name: Test Azure Login
        id: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - run: |
          az aks get-versions -l eastus -o table
          echo "Deleting existing AKS cluster"
          az aks delete --yes --no-wait \
            --verbose \
            --resource-group ${{secrets.AZURE_RG}} \
            --name ${{secrets.AZURE_AKS_CLUSTER_NAME}}
            
          echo "Creating new AKS cluster..."
          az aks create --resource-group ${{secrets.AZURE_RG}} \
            --name ${{secrets.AZURE_AKS_CLUSTER_NAME}} \
            --node-count ${{secrets.AZURE_AKS_NODE_COUNT}} \
            --node-vm-size ${{secrets.AZURE_AKS_NODE_VM_SIZE}} \
            --kubernetes-version ${{secrets.AZURE_AKS_VERSION}} \
            --generate-ssh-keys
            
          echo "Cluster created successfully!"

      
