name: GitHub Actions Demo for V8o on Azure
on: [push]
env:
  azCliVersion: 2.6.0
jobs:
  azure_login:
    runs-on: ubuntu-latest
    steps:
      - name: Test Azure Login
        id: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: List AKS clusters
        id: aks-cluster-list
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.azCliVersion }}
          inlineScript: |
            az aks list
