name: GitHub Actions Demo for V8o on Azure
on: [push]
env:
  azCliVersion: 2.6.0
jobs:
  azure_login:
    runs-on: ubuntu-latest
    steps:
      - name: Test Azure Login
        id: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create SSH files
        run: |
          ssh-keygen -t rsa -b 2048 -f ~/.ssh/gitaction_rsa -q -P ${{secrets.AZURE_SSH_KEYGEN_PASS}}
          
      - name: Create AKS cluster
        id: aks-cluster-list
        uses: azure/CLI@v1
        with:
          azcliversion: ${{ env.azCliVersion }}
          inlineScript: |
            az aks list

            echo "Deleting existing AKS cluster"
            az aks delete \
              --yes \
              --no-wait \
              --verbose \
              --resource-group ${{secrets.AZURE_RG}} \
              --name ${{secrets.AZURE_AKS_CLUSTER_NAME}}
            
            echo "Create AKS cluster"
            az aks create \
              --resource-group ${{secrets.AZURE_RG}} \
              --name ${{secrets.AZURE_AKS_CLUSTER_NAME}} \
              --node-count ${{secrets.AZURE_AKS_NODE_COUNT}} \
              --generate-ssh-keys \
              --node-vm-size ${{secrets.AZURE_AKS_NODE_VM_SIZE}} \
              --kubernetes-version ${{secrets.AZURE_AKS_VERSION}}            
            
      # Set the AKS cluster context
      - name: Set the AKS cluster context
        uses: Azure/aks-set-context@v1
        if: github.event_name == 'commit'
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{secrets.AZURE_AKS_CLUSTER_NAME}}
          resource-group: ${{secrets.AZURE_RG}}
