name: GitHub Actions Demo
on: [push]
jobs:
  test_curl:
    runs-on: ubuntu-latest
    steps:
      - name: Get IP of build machine
        id: get-ip-address
        run: |
          myIP=$(dig @ns1.google.com TXT o-o.myaddr.l.google.com +short)
          echo "myIP=${myIP}"
          echo "myIP=${myIP}" >> GITHUB_ENV
      - name: Invoke curl
        run: |
          curl -k -v https://${{secrets.VZ_CONSOLE_URL}}
          ping $myIP
      - name: Get Verrazzano console status
        uses: wei/curl@master
        with:
          args: https://${{secrets.VZ_CONSOLE_URL}}
