name: GitHub Actions Demo for V8o on Azure
on: [push]
env:
  azCliVersion: 2.6.0
jobs:
  azure_login:
    runs-on: ubuntu-latest
    steps:
      - name: Test Azure Login
        id: azure-login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set the AKS cluster context
        uses: Azure/aks-set-context@v1
        #if: github.event_name == 'commit'
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
          cluster-name: ${{secrets.AZURE_AKS_CLUSTER_NAME}}
          resource-group: ${{secrets.AZURE_RG}}

      - name: Run kubectl
        run: |
          kubectl get nodes -o wide
