name: Test checkout
on:
  workflow_call:
    inputs:
      VZ_CRD_FILENAME:
        required: false
        type: string
      CUSTOM_CA_OPTION:
        required: false
        type: string
jobs:
  test_checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Export env
        run: |
          echo "CUSTOM_CA_OPTION=${{inputs.CUSTOM_CA_OPTION}}" >> $GITHUB_ENV

      - name: Checkout develop branch
        uses: actions/checkout@v2
        with:
          ref: develop
      
      - name: Run if option is true
        if: contains(inputs.CUSTOM_CA_OPTION, 'true')
        run: |
          echo "Custom CA option is true"
          echo $(pwd)
          cat ${{ inputs.VZ_CRD_FILENAME }}
          echo ${{inputs.CUSTOM_CA_OPTION}}
      
      - name: Run if option is false
        if: contains(inputs.CUSTOM_CA_OPTION, 'false')
        run: echo "Custom CA option is false"          
